deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - git config --global user.email "martin.lauterbach@student.reutlingen-university.de"
    - git config --global user.name "mklemmingen"
    - git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/mklemmingen/KatzenKaffeeWeb.git
    - git fetch --unshallow || true
    - git checkout main
    - git push origin +main  # Force push to GitHub without pulling
    - echo "Application successfully deployed."
  environment: production
  only:
    - main